services:
  - type: web
    name: expenso-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 3 expenso_backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: expenso-db
          property: connectionString

databases:
  - name: expenso-db
    databaseName: expenso
    user: expenso_user